#!/bin/bash

# To install the precommit hook, you need to run this following
# cp ~/.dotfiles/dotfiles-precommit-hook ~/.dotfiles/.git/hooks/pre-commit

dotfiles_dir="$HOME"/.dotfiles
if [ "$PWD" = "$dotfiles_dir" ]; then
  save_code_extensions
  git add vscode/code_extensions
fi
